baseurl = "https://qingmao-cell.github.io/"
title = "Blue Seal"
theme = "PaperMod"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# # (Optional) Set Google Analytics if you use it to track your website.
# # Always put it on the top of the configuration file, otherwise it won't work
# googleAnalytics = "UA-XXXXXXXXX-X"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
# disqusShortname = "my-site"

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# # (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# # You can remove related files with config below
# disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  # Theme settings
  defaultTheme = "dark"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false
  ShowToc = true
  TocOpen = false
  disableShare = true

  # Profile Mode (Portfolio)
  [params.profileMode]
    enabled = true
    title = "Blue Seal"
    subtitle = "Software Developer | Creative Technologist"
    imageUrl = "/logo.png"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "Profile Picture"
    
    [[params.profileMode.buttons]]
      name = "Portfolio"
      url = "/portfolio"
    [[params.profileMode.buttons]]
      name = "About"
      url = "/about"

  # Home Info (disabled when profileMode is enabled)
  # [params.homeInfoParams]
  #   Title = "Welcome"
  #   Content = "コードとデザインで、心地よいデジタル体験を創り出します。"

  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/qingmao-cell"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:arisakiryo@gmail.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 15
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  # [[menu.main]]
  #   name = "Blog"
  #   url = "/posts/"
  #   weight = 30
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 40